server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: productModule
        uri: lb://produtos
        predicates:
        - Path=/produtos/**