INSERT INTO ENTREGA (ID_PEDIDO, PREVISAO_DE_ENTREGA, ENDERECO_DE_ORIGEM, ENDERECO_DESTINATARIO) VALUES(11, '31/03/2022', 'Rua São Paulo', 'Rua Campina');
INSERT INTO ENTREGA (ID_PEDIDO, PREVISAO_DE_ENTREGA, ENDERECO_DE_ORIGEM, ENDERECO_DESTINATARIO) VALUES(89, '14/04/2022', 'Rua Maciel Pinheiro', 'Rua Brasília');
