server:
  port: 8765

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: clientes
          uri: 'http://localhost:8082'
          predicates:
            - Path=/clientes/**
        - id: entregas
          uri: 'http://localhost:8083'
          predicates:
            - Path=/entregas/**
        - id: lojas
          uri: 'http://localhost:8081'
          predicates:
            - Path=/lojas/**